In [2]:
import pandas as pd

data = {
"Name": ["Alice", "Bob", "Charlie"],
"Dept": ["HR", "Finance", "IT"],
"Sal": [60000, 70000, 80000],
}

df = pd.DataFrame(data)

Exercise 1 - Rename Dept to Department and Sal to Salary

In [5]:
df.rename(columns={
    'Dept': 'Department',
    'Sal': 'Salary'
}, inplace=True)
df

      Name Department  Salary
0    Alice         HR   60000
1      Bob    Finance   70000
2  Charlie         IT   80000

Exercise 2 - Reorder columns so Salary appears first, followed by Name and Department.

In [6]:
df_reordered = df[['Salary', 'Name', 'Department']]

Excersise 3 - Show expected output for Reordering Columns.

In [7]:
df_reordered

   Salary     Name Department
0   60000    Alice         HR
1   70000      Bob    Finance
2   80000  Charlie         IT