In [1]:
import pandas as pd

data = {
"Store": ["A", "A", "A", "B", "B", "C", "C", "C", "C"],
"Product": ["Apples", "Oranges", "Bananas", "Apples", "Bananas", "Oranges", "Apples", "Bananas", "Bananas"],
"Sales": [100, 80, 90, 120, 110, 60, 95, 85, 75],
"Profit": [30, 25, 20, 40, 35, 15, 32, 22, 18],
}

df = pd.DataFrame(data)
print(df.head())

  Store  Product  Sales  Profit
0     A   Apples    100      30
1     A  Oranges     80      25
2     A  Bananas     90      20
3     B   Apples    120      40
4     B  Bananas    110      35

Excercise 1 - Group the data by `Store` and use `.agg()` to find the aveage `Sales` and average `Profit` for each store.

In [3]:
df.groupby('Store').agg({
    'Sales': 'mean',
    'Profit':'mean'
})

        Sales  Profit
Store
A       90.00   25.00
B      115.00   37.50
C       78.75   21.75

Excercise 2 - Group by `Product` and get the maximum `Sales` and minimum `Profit`

In [4]:
df.groupby('Product').agg({
    'Sales': 'max',
    'Profit': 'min'
})

         Sales  Profit
Product
Apples     120      30
Bananas    110      18
Oranges     80      15

Excercise 3 - Group by `Store` and return the average `Sales` and maximum `Profit`, but name the columns `Avg_Sales` and `Max_Profit`.

In [5]:
df.groupby('Store').agg(
    Avg_Sales=('Sales', 'mean'),
    Max_Profit=('Profit', 'max')
)

       Avg_Sales  Max_Profit
Store
A          90.00          30
B         115.00          40
C          78.75          32

BONUS: Group by both `Store` and `Product`, and find the total `Sales` using `.agg()`.

In [12]:
df.groupby(['Store', 'Product']).agg({
    'Sales': 'sum'
})

               Sales
Store Product
A     Apples     100
      Bananas     90
      Oranges     80
B     Apples     120
      Bananas    110
C     Apples      95
      Bananas    160
      Oranges     60