In [2]:
import pandas as pd

data = {
"Name": ["Alice", "Bob", "Charlie", "Alice", "Bob", "Diana"],
"Age": [25, 30, 35, 25, 30, 40],
"City": ["NYC", "LA", "SF", "NYC", "LA", "NYC"],
}

df = pd.DataFrame(data)

Exercise 1 - Find which rows are duplicates across all columns.

In [ ]:
df.duplicated()

Exercise 2 - Drop duplicate rows, keeping the first occurrence.

In [ ]:
df_cleaned = df.drop_duplicates()
df_cleaned

Excersise 3 - Drop duplicate rows, keeping only the last occurrence.

In [7]:
df_cleaned = df.drop_duplicates(keep='last')
df_cleaned

      Name  Age City
2  Charlie   35   SF
3    Alice   25  NYC
4      Bob   30   LA
5    Diana   40  NYC

Excersise 4 - Drop all duplicates, removing the original and duplicate rows.

In [3]:
df_cleaned = df.drop_duplicates(keep=False)
df_cleaned

      Name  Age City
2  Charlie   35   SF
5    Diana   40  NYC